### ISSUE TITLE
Problème d'execution

### ISSUE THREAD

**Issue by jchomaz** [Naviss53/MDT_AUTOLOGON#1]
Salut Naviss53, 

Tout d'abord merci pour ce beau petit code bien pratique, cependant je me pose une question.
Si ton script est exécuté par MDT, MDT attendra la fin de l'exécution de ce programme pour terminer son déploiement.. mais vu que l'exe attend la fin de l'exécution du déploiement du coup c'est un boucle sans fin .. tu n'a pas eu ce pb ?

**Comment by Naviss53** [comment]
Bonjour jchomaz,
Cela fait un moment que je n'ai plus utilisé MDT, je suis passé sur MECM.
Je n'ai jamais eu de soucis en veillant à lancer le script avec une etape "Run command line" et en passant la commande du type : 
cmd.exe /C start %SCRIPTROOT%\MDT_AUTOLOGON.exe toto totopass totodomain

En ne mettant pas de /wait dans la commande, l'etape "Run command line" va lancer le processus cmd.exe qui lui même va lancer l'executable sans attendre sa fin d'execution et va se fermer et renvoyer un code de retour à MDT qui indiquera la fin d'execution de l'etape "run command line".

Maintenant c’était il y a un moment et je ne sais pas si la façon de fonctionner de MDT a changé ou non.

**Comment by jchomaz** [comment]
Et oui c'est vrai que cmd.exe /C start n'attend pas de suite ! Quel idiot je suis, j'ai testé sans.

Et non MDT fonctionne toujours de la même manière. :D 

Merci pour ton retour ! 

Bonne journée et bon week-end ! :)

**Comment by Naviss53** [comment]
Pas de soucis. 
Effectivement si l’exécutable est lancé directement sans le "cmd /C start", l’étape ne se terminera jamais (du moins jusqu'à un timeout).
C'est pour ça que pour l’intégration dans une séquence de tâches MDT, je précise d'utiliser la commande "cmd /C start" pour éviter ce problème d'exécution infinie.
